// Builds the single-file, click-and-run package: openatlas.exe
//
//   1. Builds the React UI into app/ui/dist
//   2. Generates app/ui-assets.ts  (embedded asset manifest, `with { type: "file" }`)
//   3. Generates app/build-info.ts  (PACKAGED marker + version)
//   4. Compiles app/server.ts into a standalone executable that embeds the UI
//      and opens the browser on launch.
//
// Usage:  bun run package
import { spawnSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";

const root = path.resolve(import.meta.dir, "..");
const uiDir = path.join(root, "app", "ui");
const distDir = path.join(uiDir, "dist");
const assetsTs = path.join(root, "app", "ui-assets.ts");
const buildInfoTs = path.join(root, "app", "build-info.ts");
const outDir = path.join(root, "dist-package");
const outExe = path.join(outDir, process.platform === "win32" ? "openatlas.exe" : "openatlas");

function run(cmd: string, args: string[], cwd: string): void {
  console.log(`$ ${cmd} ${args.join(" ")}`);
  const res = spawnSync(cmd, args, { cwd, stdio: "inherit", shell: process.platform === "win32" });
  if (res.status !== 0) {
    console.error(`command failed (${res.status ?? res.signal}): ${cmd} ${args.join(" ")}`);
    process.exit(1);
  }
}

console.log("\n[1/4] building UI...");
run("bun", ["run", "--cwd", "app/ui", "build"], root);

console.log("\n[2/4] generating embedded asset manifest...");
const files: string[] = [];
function walk(dir: string): void {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else files.push(full);
  }
}
walk(distDir);
if (files.length === 0) {
  console.error("UI build produced no files in app/ui/dist");
  process.exit(1);
}

const entries: string[] = [];
files.sort().forEach((file) => {
  const rel = path.relative(distDir, file).split(path.sep).join("/");
  const key = `/${rel}`;
  const data = fs.readFileSync(file).toString("base64");
  entries.push(`${JSON.stringify(key)}: ${JSON.stringify(data)},`);
});
const assetsCode = `// GENERATED by scripts/package.ts — do not edit.
// Base64-embedded UI assets. Inlined as plain strings (not import-with-file
// style) so the compiled bundle never depends on bun's asset import behavior,
// which breaks when the module count or minifier changes.
const assets: Record<string, string> = {
${entries.join("\n")}
};
export { assets };
`;
fs.writeFileSync(assetsTs, assetsCode);
console.log(`  embedded ${files.length} UI files`);

console.log("\n[3/4] generating build info...");
fs.writeFileSync(
  buildInfoTs,
  `// GENERATED by scripts/package.ts — do not edit.
const PACKAGED = true;
const VERSION = ${JSON.stringify(JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8")).version)};
const BUILD_DATE = ${JSON.stringify(new Date().toISOString())};
export { PACKAGED, VERSION, BUILD_DATE };
`
);

console.log("\n[4/4] compiling openatlas...");
fs.mkdirSync(outDir, { recursive: true });
run("bun", ["build", "app/server.ts", "--compile", "--outfile", outExe], root);

// Restore the committed dev defaults for the generated modules so plain
// `bun app/server.ts` development keeps using the on-disk app/ui/dist (and
// never auto-opens a browser). The defaults must exist in the repo — the
// compiled binary needs static imports that resolve at build time.
fs.writeFileSync(
  assetsTs,
  `// Dev default (regenerated by scripts/package.ts at package time).
const assets: Record<string, string> = {};
export { assets };
`
);
fs.writeFileSync(
  buildInfoTs,
  `// Dev default (regenerated by scripts/package.ts at package time).
const PACKAGED = false;
const VERSION = "0.1.0";
const BUILD_DATE = "";
export { PACKAGED, VERSION, BUILD_DATE };
`
);

const size = fs.statSync(outExe).size;
console.log(`\npackaged: ${outExe} (${(size / 1024 / 1024).toFixed(1)} MB)`);
console.log("run it by double-clicking, or: " + outExe);
