import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const distDir = join(import.meta.dir, "..", "dist");
const outFile = join(import.meta.dir, "..", "server", "embedded-assets.ts");
const root = join(import.meta.dir, "..");

function walk(dir, prefix = "") {
  const out = {};
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const key = `${prefix}${name}`;
    if (statSync(full).isDirectory()) {
      Object.assign(out, walk(full, `${key}/`));
    } else {
      const b64 = readFileSync(full).toString("base64");
      out[key] = `data:application/octet-stream;base64,${b64}`;
    }
  }
  return out;
}

const assets = walk(distDir);
const hostFile = join(import.meta.dir, "..", "server", "pty-host.mjs");
if (existsSync(hostFile)) {
  assets["__internal/pty-host.mjs"] = `data:application/octet-stream;base64,${readFileSync(hostFile).toString("base64")}`;
}

// Embed a runtime node-pty for Windows x64 so the single exe works in a bare dir.
// Only the JS lib and the win32-x64 prebuilds are needed; skip tests/maps.
function embedNodePty() {
  const ptyRoot = join(root, "vendor", "node-pty");
  if (!existsSync(ptyRoot)) return;
  const keep = (rel) => {
    if (rel.endsWith(".pdb")) return false;
    if (rel.startsWith("lib/")) return !rel.endsWith(".test.js") && !rel.endsWith(".map");
    if (rel.startsWith("prebuilds/win32-x64/")) return true;
    return false;
  };
  const walkRel = (dir, rel) => {
    for (const name of readdirSync(dir)) {
      const full = join(dir, name);
      const r = `${rel}${name}`;
      if (statSync(full).isDirectory()) {
        walkRel(full, `${r}/`);
      } else if (keep(r)) {
        assets[`__vendor/node-pty/${r}`] = `data:application/octet-stream;base64,${readFileSync(full).toString("base64")}`;
      }
    }
  };
  walkRel(ptyRoot, "");
}
embedNodePty();

// Embed the vendored opencode binary so the single exe works in a bare dir.
function embedOpencode() {
  const exe = join(root, "vendor", "opencode", "bin", process.platform === "win32" ? "opencode.exe" : "opencode");
  if (!existsSync(exe)) {
    console.warn("vendor/opencode missing — skipping embed. opencode will not be on PATH in the exe.");
    return;
  }
  assets["__vendor/opencode/bin/" + exe.split(/[\\/]/).pop()] =
    `data:application/octet-stream;base64,${readFileSync(exe).toString("base64")}`;
}
embedOpencode();

const keys = Object.keys(assets);
if (!keys.length) {
  console.error("dist/ is empty — run `bun run build` first");
  process.exit(1);
}

const lines = [
  '// GENERATED by scripts/embed-assets.mjs — do not edit by hand.',
  'export const ASSETS: Record<string, string> = {',
  ...keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(assets[k])},`),
  "};",
  "",
];
writeFileSync(outFile, lines.join("\n"));
console.log(`embedded ${keys.length} files -> server/embedded-assets.ts (${keys.length > 0 ? Math.round(readFileSync(outFile).length / 1024) : 0} KB)`);
